name: vision_bias
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.20
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.5
  - scikit-learn=1.3.2
  - torch=1.10.1
  - torchvision=0.11.2
  - mmcv
  - mmengine
  - transformers
  - opencv-python=4.11.0.86
  - grad-cam>=1.3.6
  - pip:
      - pickle-mixin
      - tqdm
