name: vision_bias
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8.20
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.5
  - scikit-learn=1.3.2
  - opencv-python=4.11.0.86
  - grad-cam>=1.3.6
  - pip:
      - pickle-mixin
      - tqdm
  - pip:
      - mmengine
      - mmcv
      - transformers
      - torch
      - torchvision
