name: vision_bias
channels:
  - pytorch
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.8.20
  - cudatoolkit=11.3.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - executing=2.1.0
  - freetype=2.13.3
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lcms2=2.15
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.6
  - libfreetype
  - libpng=1.6.47
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libtiff=4.5.0
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - msys2-conda-epoch=20160418=1
  - nest-asyncio=1.6.0
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.5.2
  - openssl=3.5.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - python=3.8.20
  - python_abi=3.8=7_cp38
  - pytorch=1.10.1=py3.8_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pyzmq=25.1.2
  - sqlite=3.49.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.13
  - torchvision=0.11.2=py38_cu113
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd
  - pip:
      - absl-py==2.2.2
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - astunparse==1.6.3
      - cachetools==5.5.2
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==44.0.3
      - cycler==0.12.1
      - einops==0.8.1
      - filelock==3.14.0
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - gast==0.4.0
      - google-auth==2.40.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grad-cam==1.5.5
      - grpcio==1.70.0
      - h5py==3.11.0
      - huggingface-hub==0.31.2
      - idna==3.10
      - importlib-resources==6.4.5
      - jmespath==0.10.0
      - joblib==1.4.2
      - keras==2.13.1
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mat4py==0.6.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mmengine==0.10.7
      - model-index==0.1.11
      - modelindex==0.0.2
      - oauthlib==3.2.2
      - opencv-python==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - opt-einsum==3.4.0
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.3
      - pillow==10.4.0
      - protobuf==4.25.7
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pycryptodome==3.22.0
      - pygments==2.19.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pywin32==310
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - rich==13.4.2
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - setuptools==60.2.0
      - six==1.17.0
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-intel==2.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - tqdm==4.65.2
      - transformers==4.46.3
      - ttach==0.0.3
      - typing-extensions==4.5.0
      - tzdata==2025.2
      - urllib3==1.26.20
      - werkzeug==3.0.6
      - wrapt==1.17.2
      - yapf==0.43.0
      - zipp==3.20.2
prefix: C:\Users\crane\anaconda3\envs\open-mmlab